Dataset: datasets\data_132v_100x80
Config: cfg_1
Tempo de execução: 0.54 segundos

=== Saída ===
pygame 2.6.1 (SDL 2.28.4, Python 3.13.0)
Hello from the pygame community. https://www.pygame.org/contribute.html

=== Erros ===
Traceback (most recent call last):
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\mas\main.py", line 50, in <module>
    main(data_folder_name, config_ag_folder_name)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\mas\main.py", line 30, in main
    Explorer(env, explorer_file, master_rescuer)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\mas\explorer.py", line 96, in __init__
    self.move_to_initial_quadrant()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MATHEUS.VPS\Repos\Personal\VictimSim2\mas\explorer.py", line 104, in move_to_initial_quadrant
    target_x = int(map_width * (self.quadrant_limits['x'][0] + self.quadrant_limits['x'][1]) / 2)
                                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Explorer' object has no attribute 'quadrant_limits'
